# Generated by Django 4.0 on 2022-01-03 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamada', models.CharField(max_length=150)),
                ('mês', models.CharField(max_length=3)),
                ('dia', models.CharField(max_length=2)),
                ('conteúdo', models.TextField()),
                ('feature', models.BooleanField(default=False)),
                ('data_criação', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
